services:
  champdf:
    # simple mode - champdf/champdf-simple:latest
    # default mode - champdf/champdf:latest
    image: champdf/champdf-simple:latest
    container_name: champdf
    restart: unless-stopped
    ports:
      - '8080:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
